use_frameworks!

target 'AYTypeWriter_Example' do
  pod 'AYTypeWriter', :path => '../'

  target 'AYTypeWriter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
